// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CarsColumns holds the columns for the "cars" table.
	CarsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "model", Type: field.TypeString},
		{Name: "country", Type: field.TypeString},
		{Name: "icon_url", Type: field.TypeString},
	}
	// CarsTable holds the schema information for the "cars" table.
	CarsTable = &schema.Table{
		Name:       "cars",
		Columns:    CarsColumns,
		PrimaryKey: []*schema.Column{CarsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "phonenumber", Type: field.TypeString},
		{Name: "photo_url", Type: field.TypeString},
		{Name: "car", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// CarCarsownedColumns holds the columns for the "car_carsowned" table.
	CarCarsownedColumns = []*schema.Column{
		{Name: "car_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// CarCarsownedTable holds the schema information for the "car_carsowned" table.
	CarCarsownedTable = &schema.Table{
		Name:       "car_carsowned",
		Columns:    CarCarsownedColumns,
		PrimaryKey: []*schema.Column{CarCarsownedColumns[0], CarCarsownedColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "car_carsowned_car_id",
				Columns:    []*schema.Column{CarCarsownedColumns[0]},
				RefColumns: []*schema.Column{CarsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "car_carsowned_user_id",
				Columns:    []*schema.Column{CarCarsownedColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CarsTable,
		UsersTable,
		CarCarsownedTable,
	}
)

func init() {
	CarCarsownedTable.ForeignKeys[0].RefTable = CarsTable
	CarCarsownedTable.ForeignKeys[1].RefTable = UsersTable
}
